# Generated by Django 4.0.4 on 2022-07-12 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_estado_orden',
            },
        ),
        migrations.CreateModel(
            name='ItemsCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=60)),
                ('precio_producto', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='items_carro')),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField(blank=True)),
                ('usuario', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_items_carro',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('articulos', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado_pedido', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_orden',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('cod_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_registro',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('cod_log', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuarioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_usuario', models.IntegerField(choices=[[0, 'Normal'], [1, 'Suscrito']])),
                ('imagen', models.ImageField(null=True, upload_to='suscritos')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=9)),
                ('dv_run', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=80)),
                ('suscripcion', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='usuarios')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('usuarioDjango', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_usuario_extra',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
            options={
                'db_table': 'db_producto',
            },
        ),
    ]
