# Generated by Django 4.0.1 on 2022-05-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemscarro',
            old_name='created_at',
            new_name='creado',
        ),
    ]
